name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Debug flake8 configuration
        # Outputs flake8 version and configuration paths for debugging
        run: flake8 --version

      - name: Run linter
        # Specify max-line-length directly to avoid config issues
        run: flake8 --max-line-length=120 models/ tests/

  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        # Run tests with pytest and generate test result files
        run: pytest --cov=app --cov-report=xml --junitxml=pytest-results.xml

      - name: Upload test results
        # Upload pytest results for review
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: pytest-results.xml

      - name: Upload coverage report
        # Upload coverage report for review
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deployment placeholder
        # Replace this placeholder with actual deployment logic
        run: echo "Deploy application (placeholder step)"
